### ISSUE TITLE
Supply list

### ISSUE THREAD

**Issue by stephwright** [daniellecrobinson/mini-wow-pdx#10]
- [x] quarter sheet lined post-its https://www.amazon.com/Post-Sticky-Janeiro-Collection-4621-SSAU/dp/B001UXFT70/
- [x] red & green post-its https://www.amazon.com/dp/B008PAIFU4/ & https://www.amazon.com/dp/B008PAIDO2/
- [x] name tags https://www.amazon.com/Badges-Wisdompro-Printable-Magnetic-Jacket/dp/B01MRTZYW5/
- [x] writing utensils 
  - [x] dry erase markers https://www.amazon.com/Low-Odor-Markers-Assorted-Colors-8-Count/dp/B000Z88D2E/
  - [x] ballpoint pens 
  - [x] Sharpies https://www.amazon.com/Sharpie-Permanent-Markers-Assorted-Colors/dp/B000F9XBQQ/
- [x] open canvas printout (Daniela)

**Comment by stephwright** [comment]
@daniellecrobinson can you look at the links above and see if they fit your needs.  If so, I'll put in the order.

**Comment by stephwright** [comment]
Oooh!!!  Found a post-it easel pad for $19!!! will buy it

**Comment by daniellecrobinson** [comment]
I just bought wine, beer, chips and hummus, fruit, and lacroix. I also got ice for tomorrow (I can bring a cooler to keep drinks and snacks cold)

**Comment by daniellecrobinson** [comment]
The kosher for passover options were really nonexistant at Fred Meyer's - so I will need to run to Whole Foods or Kenny and Zukes (a jewish-ish deli) this afternoon to get a meal for 1 person for tonight, and ideally, another meal for them tomorrow. I do have matzoh! So, that's a start.

**Comment by daniellecrobinson** [comment]
Beer and wine: I got 18 assorted beers and two bottles of wine, then i decided that wasn't enough and bought two more wines myself (which I can use for my passover party on sunday if we don't need them)

**Comment by daniellecrobinson** [comment]
I also got 6 8-packs of assorted flavor cans of lacroix which should be enough for both tonight and tomorrow (bonus  it was on sale)
