### ISSUE TITLE
Intro 5 min

### ISSUE THREAD

**Issue by daniellecrobinson** [daniellecrobinson/mini-wow-pdx#12]
@stephwright and Hannah?

**Comment by daniellecrobinson** [comment]
Slides I have used to intro Mozilla Science - https://docs.google.com/presentation/d/1mr6lnMm3cwx5AX690QyVO-I4YnQYIJEKSuqwfEwZwN8/edit#slide=id.g1a98113aeb_0_71

**Comment by stephwright** [comment]
Hannah and I have chatted... we're going slide free if that's okay.

P.S. I don't have permission to access the above slide deck :(
