### ISSUE TITLE
Identify Safety Committee

### ISSUE THREAD

**Issue by stephwright** [daniellecrobinson/mini-wow-pdx#16]
Created notes etherpad for the event and updated on homepage.

Line 18 as CoC and I listed Danielle as member... good to have a backup.  What's our process going to be on Safety Issues?

**Comment by stephwright** [comment]
NM... just found info on the homepage :)

**Comment by daniellecrobinson** [comment]
Yes, but let's check if I actually asked them to do that or if I just thought about it and never actually asked them.... @rchampieux and @teonbrooks - will you be our safety committee? :rose:

**Comment by daniellecrobinson** [comment]
@stephwright Let's go through this tomorrow? I nominated @teonbrooks  partly because he has done it before :)

**Comment by rchampieux** [comment]
@stephwright @daniellecrobinson happy to do this.

**Comment by rchampieux** [comment]
@daniellecrobinson also, you may have asked me to do this, but my mind is presently full of holes.  Presentation purgatory...it will pass soon.

**Comment by stephwright** [comment]
Yay @teonbrooks and @rchampieux ... thank you!  :bowing_woman:
