### ISSUE TITLE
Catering for Saturday

### ISSUE THREAD

**Issue by daniellecrobinson** [daniellecrobinson/mini-wow-pdx#3]
Let's review some options for catering.

**Comment by dasaderi** [comment]
Indian or Thai foods are always amazing, gluten free and vegan for the most part.

**Comment by stephwright** [comment]
+1... I like both those options.
Just so I know what we're talking... we need catering for:
- [x] Sat am coffee/donuts?
- [x] Sat lunch
- [x] Sat aft soda/snacks?

Is that everything?

**Comment by daniellecrobinson** [comment]
Hi @stephwright I emailed Hannah on Wednesday but have not heard back. You are cc'd on that email.

**Comment by daniellecrobinson** [comment]
We could let people be on their own for breakfast/coffee on saturday

**Comment by daniellecrobinson** [comment]
https://www.elephantsdeli.com/locations/flying-south-waterfront
opens at 9am Saturdays, has coffee and breakfast

There's also a starbucks open at 7am on Saturdays in the same building

**Comment by daniellecrobinson** [comment]
Though, OF COURSE, donuts are a great option.

**Comment by daniellecrobinson** [comment]
http://www.chachachapdxcatering.com/business--casual.html

**Comment by stephwright** [comment]
<3 the taco bar or fajita bar options.  Would incl sour cream, lettuce & cheese option for taco bar.  If fajita, would see if we could include beans and rice for $3/pp.

I like the idea of mexican hot chocolate and lemonade as drink options.  if there isn't water avail at water stations at facility get  bottled water too.

If folks need caffeine jolt can get coffee at Starbucks.  

Not dictating, just suggesting.
