### ISSUE TITLE
Friday night logistics

### ISSUE THREAD

**Issue by daniellecrobinson** [daniellecrobinson/mini-wow-pdx#4]
@stephwright For Friday night, We could do pizza or something (and um, possibly wine/beer? or lacroix?). 
My vision for Friday is to have an off campus location where we could do basic github (depending on who registers) and some intros.

**Comment by daniellecrobinson** [comment]
Friday vision: 

5:30-6 mingling and arrivals, pizza and drinks are available at 5:30

6:00-6:15 Intro to Mozilla Science Lab and WOW

6:15-7 Introductions and ideas - keep it low stakes - maybe everyone answers the same 5 qs about their idea? Or another ice breaker/"no imposters here" exercise to get people talking about their ideas

7-7:15 break

7:15-8:30 Let's get everyone on GitHub - basic account making and GitHub tour for people unfamiliar with it.

8:30 - we go to another bar :)

**Comment by stephwright** [comment]
@daniellecrobinson yes to pizza... need to find out what the logistics are w/ wine & beer... forgive my addled brain... what's lacroix?

**Comment by daniellecrobinson** [comment]
@stephwright http://www.lacroixwater.com/
The hipster sparking water of choice ;)
 I have emailed Hannah about Friday night!

**Comment by stephwright** [comment]
so funny... was co-working w/ a friend yesterday and she asked if I wanted a La Croix... and I knew what she meant!
