### ISSUE TITLE
High level stuff to do for WOW!

### ISSUE THREAD

**Issue by daniellecrobinson** [daniellecrobinson/mini-wow-pdx#5]
1. Friday Night Location - confirm that (DR)
2. Friday Night food - Stephanie to pizza (DR)
3. Recruit people to come
 - https://www.facebook.com/events/1761824424039971/

4. Lunch on Saturday

5. Facilitate out of town people

6. Decide on which part of WOW to do 
- assign people to lead the session
- mostly done, Stephanie and Teon

7. Panel discussion or something similar 
- Community building - recruit people

8. GitHub Pages site up (DR)

**Comment by rchampieux** [comment]
Recruiting people to go.  Jackie, GSO, Mike Matrone.

**Comment by rchampieux** [comment]
Robin will contact Jill Emery and Emily Ford at PSU.

**Comment by daniellecrobinson** [comment]
Spilt up the list for people who responded on the WOW FB

These people are "GOING":

Daniela Saderi (registered)
	
Jess Shamek  (registered)

Samantha Hindle (registered)
	
Robin Champieux
	
Asia Mitchell
	
Stephanie Wright (facilitator)
	
Ellie Juarez
	
Mary Louise

**Comment by daniellecrobinson** [comment]
These people are "INTERESTED":
Kreeya Andcoco
	
Lilly Winfree
	
Khady Sall

Cristina Chin
	
Jim Moser
	
Andrea Chin

Shaelyn Watson

Monae Verbeke
	
Chris Shaffer
	
Trish Pruis

**Comment by stephwright** [comment]
Mary Louise Gifford from Seattle Data for Good is coming.  She's driving down w/ me and staying at my Airbnb.  She said she was going to register but if she hasn't yet, now you know.

**Comment by daniellecrobinson** [comment]
SWEEET! We have four registered participants as of now.

**Comment by stephwright** [comment]
Just sent message to organizer of Women in Sci Seattle, ChickTech, and working on email to Association for Women in Science Seattle.
