### ISSUE TITLE
Recruitment of participants!

### ISSUE THREAD

**Issue by daniellecrobinson** [daniellecrobinson/mini-wow-pdx#6]
Hey! Let's all do a big push to get participants registered!

**Comment by daniellecrobinson** [comment]
@stephwright can you follow up with our Steve and Jessica?

**Comment by daniellecrobinson** [comment]
@rchampieux can you follow up with Ryer?

**Comment by dasaderi** [comment]
Okay, I'll send the email to Liz for NGP tomorrow. Do you know if Jackie is going to email it out?

**Comment by dasaderi** [comment]
Sent the email to Liz to send to NGP grads and postdocs. I'll send it out to GSO too. It won't hurt to get it twice.

**Comment by daniellecrobinson** [comment]
Thanks @dasaderi

**Comment by stephwright** [comment]
On it... and done.

**Comment by daniellecrobinson** [comment]
I have pushed this out to all my contacts at Portland State and OHSU, and did a crap-ton of flyering at OHSU yesterday. I will flyer the CLSB and PSU campuses on Monday. @dasaderi if you can - would you hang a few flyers in RJH today or monday?

**Comment by daniellecrobinson** [comment]
@rchampieux can you reach out to the PSU librarians?

**Comment by rchampieux** [comment]
Yes, no problem.  I will do it today.

**Comment by rchampieux** [comment]
Also, apologies, I'm behind on WOW outreach / AI, but will dive in today and this weekend.

**Comment by rchampieux** [comment]
Also, following up with Ryer today.

**Comment by daniellecrobinson** [comment]
I emailed Chester Ismay at Reed... does anyone know other Reed contacts?

**Comment by daniellecrobinson** [comment]
Flyer is here: https://github.com/daniellecrobinson/mini-wow-pdx/blob/master/miniWOW%20PDX.pdf

**Comment by rchampieux** [comment]
Yes, I am actually meeting with a former Reed librarian, now Dean at U of Portland, this afternoon.  I'll ask her for outreach suggestions for both orgs.

**Comment by daniellecrobinson** [comment]
Here is the text of the email I have been sending: 

Hi Chester 

We met when Hadley Wickham came to Reed earlier in the academic year. 

I want to invite you to attend - and invite you to share - an event Mozilla Science, the OHSU Library, and Women in Science Portland are sponsoring. This event helps people with an idea for a project that will help the scientific community get that project from concept to launch – details below and here. It also focuses on developing “soft skills", like project management, setting up a project to welcome participants and contributors, and building community. Please contact me if you have questions and please share with your networks! I’d love get some Reed students and faculty/staff to attend -  people are coming from UCSF, Stanford, UW, and OSU for this event! 

All you need is an idea to attend! Please share and let me know if there’s a way to get this distributed widely at Reed. 

THANK YOU!

-Danielle
— 
Danielle C. Robinson, PhD
2016 Fellow @MozillaScience 
Oregon Health & Science University
@daniellecrobins 

-----


Do you have an idea for a project .. the rest is copied from the readme!

**Comment by dasaderi** [comment]
I can do flyers in RJH on Monday. Leaving now for med appointment.

**Comment by dasaderi** [comment]
Doing flyers at RJH now. I sent the email to GSO, but I did not get a reply.
