### ISSUE TITLE
Finalize who will lead each session

### ISSUE THREAD

**Issue by daniellecrobinson** [daniellecrobinson/mini-wow-pdx#7]
Current schedule is a draft, let's review sessions one more time and finalize the details. Then session leaders can review their materials and make any new slides or tweaks to exercises.

**Comment by daniellecrobinson** [comment]
Hey y'all! Can you check out this?
https://github.com/daniellecrobinson/mini-wow-pdx/blob/master/mini-wow-pdx-schedule.md
@teonbrooks I made this before i knew you were coming. I added you to the panel discussion - is there a session you want to lead? Roadmapping? Readme? You can also join me on running the GitHub on Friday.

**Comment by dasaderi** [comment]
I like it. I can't decide if the README should be put after the Open Canvas and swapped with the roadmapping in the schedule or not.

**Comment by stephwright** [comment]
I like the order actually... they work on identifying who they are writing to and the plan in the Open Canvas and roadmapping pieces, then in the README piece, they figure out how to explain it to others.  Totally want to insert a 15 minutes piece on dejargoning in this session.

**Comment by teonbrooks** [comment]
I would be happy to help on Friday with the GitHub. I can lead the Roadmapping if you would like
