### ISSUE TITLE
Friday night icebreaker: Decide on the three Qs about your project icebreaker

### ISSUE THREAD

**Issue by daniellecrobinson** [daniellecrobinson/mini-wow-pdx#8]
Instead of having people tell us about their projects, let's brainstorm on 3 Qs that each participant can answer. This will make it less pressure on people who do not have a pitch prepared for their idea and hopefully help to break the ice. Put your Q ideas in the comments and we can thumbs up our faves.

**Comment by daniellecrobinson** [comment]
What do you want this idea to change or impact?

**Comment by daniellecrobinson** [comment]
What is unique about your project for people who might participate in it?

**Comment by daniellecrobinson** [comment]
What is a project or that you admire? What would you like to borrow or emulate in your project?

**Comment by dasaderi** [comment]
I love this idea! 
Q1: What's your project/idea about? 
Q2: Why do you think is important?
Q3: Have you been inspired by another project? If yes, what would you like to borrow from it?

**Comment by stephwright** [comment]
Maybe add to Q2... what will does your ideal scenario look like if your project succeeds?  The pie in the sky scenario of success?

**Comment by teonbrooks** [comment]
what led you to start this project? what gap does it fill?

**Comment by daniellecrobinson** [comment]
3 Qs: 
1. What led you to start this project? What gap does it fill?
2. What is a project that you admire and what would you like to borrow or emulate in your project?
3. What does your ideal scenario look like if your project succeeds - the pie in the sky scenario of success?
 
Does everyone like these questions? @teonbrooks @dasaderi @stephwright @rchampieux :heart:

**Comment by stephwright** [comment]
I like these a lot though a little worried abt Q2.  How long will they have to think about these?  That one seems like it may be a tough one to answer.

**Comment by rchampieux** [comment]
Good point about no. 2, I've seen that kind of question silence a room before.  It might be friendlier/less pressure if we generalize it a bit.  Something like, Are there projects that you've looked to for inspiration?

**Comment by dasaderi** [comment]
I like the Qs and Robin's version of Q2. Qs can be a bit intimidating at first but if no one jumps in, I can start answering them for the Open Leadership project just to start the conversation.

**Comment by stephwright** [comment]
This group is so awesome... pardon me while I gush. 😍

**Comment by daniellecrobinson** [comment]
Editing it! Love @rchampieux suggestion! Thanks everyone!!!!

**Comment by teonbrooks** [comment]
icebreaker was a success! closing
